### ISSUE TITLE
Native Language

### ISSUE THREAD

**Issue by Ca7iburn** [MadCoder253/GCA5Roll20Exporter#7]
A second language is exported at double the cost. The export has an extra native language at 6 for spoken and 6 for written. When importing into roll20 it results in a cost of 12. For Accented it was 4 for spoken and 4 for written, resulting in a cost of 8 and roll20 setting it to native based on the cost.

**Comment by Ca7iburn** [comment]
Looks like this was fixed, but GCA5 did not pull the new version yet.

**Comment by MadCoder253** [comment]
That's funny I just started doing some updates today. I asked Armin to get the update when he has time.
